INSERT INTO orders.order_status (id, name) VALUES (1, 'Pre-admisión');
INSERT INTO orders.order_status (id, name) VALUES (2, 'En camino');
INSERT INTO orders.order_status (id, name) VALUES (3, 'En entrega');
INSERT INTO orders.order_status (id, name) VALUES (4, 'Entregado');
INSERT INTO orders.order_status (id, name) VALUES (5, 'El envío ha tenido admisión en origen');
INSERT INTO orders.order_status (id, name) VALUES (6, 'Envío clasificado en centro logístico');
INSERT INTO orders.order_status (id, name) VALUES (7, 'En tránsito Correos');
INSERT INTO orders.order_status (id, name) VALUES (8, 'Llegada a la oficina de destino');
INSERT INTO orders.order_status (id, name) VALUES (9, 'Alta en unidad de reparto');
INSERT INTO orders.order_status (id, name) VALUES (10, 'En reparto');
INSERT INTO orders.order_status (id, name) VALUES (11, 'En proceso de entrega');
INSERT INTO orders.order_status (id, name) VALUES (12, 'Redireccionando o encaminando correos');
INSERT INTO orders.order_status (id, name) VALUES (13, 'Realizando intento de entrega');
INSERT INTO orders.order_status (id, name) VALUES (14, 'A disposición del destinatario');
INSERT INTO orders.order_status (id, name) VALUES (15, 'Retorno a remitente o en proceso de devolución');
INSERT INTO orders.order_status (id, name) VALUES (16, 'En oficina de cambio');
INSERT INTO orders.order_status (id, name) VALUES (17, 'Salida de la oficina internacional de origen');
INSERT INTO orders.order_status (id, name) VALUES (18, 'Salida de oficina de cambio');
INSERT INTO orders.order_status (id, name) VALUES (19, 'Llegada a la oficina internacional de destino');
INSERT INTO orders.order_status (id, name) VALUES (20, 'Pendiente de tramitación aduanera');
INSERT INTO orders.order_status (id, name) VALUES (21, 'En tramitación aduanera');
INSERT INTO orders.order_status (id, name) VALUES (22, 'Finalizada tramitación aduanera');
INSERT INTO orders.order_status (id, name) VALUES (23, 'Llegada a oficina de cambio');
INSERT INTO orders.order_status (id, name) VALUES (24, 'Salida de oficina de cambio de destino');
INSERT INTO orders.order_status (id, name) VALUES (25, 'En trámite de importación');
INSERT INTO orders.order_status (id, name) VALUES (26, 'Recibida documentación del destinatario');
INSERT INTO orders.order_status (id, name) VALUES (27, 'Recibida la transferencia');